### ISSUE TITLE
Computer configuration problem

### ISSUE THREAD

**Issue by yangxueqianR** [fmaseda/DEEPsc#1]
Hello, I would like to ask if there are any requirements for computer configuration to run DEEPSC

**Comment by fmaseda** [comment]
DEEPsc only requires an up to date MATLAB installation, along with the Deep Leaning Toolbox. The Parallel Computing Toolbox is also recommended.

**Comment by yangxueqianR** [comment]
When I followed the code training sample of your tests, I got an error and it showed insufficient memory. My computer's memory is 32G, so I would like to ask whether there is any requirement on the computer memory

**Comment by fmaseda** [comment]
32 GB RAM should be WAY more than sufficient to run the follicle example script. The follicle reference atlas is only 233 positions by 8 genes so only takes up a total of ~14 kB, and the accompanying scRNAseq dataset only takes up about 4 MB I'm pretty sure. When running, the script does create a 4D array of all pairwise combinations of atlas positions, which would be a 2*8*233^2 array taking up about 7 MB of memory. Even if you use the parallel toolbox, which creates a copy of that 4D array for each core, as long as you don't have an absurd amount of cores running at the same time (mine works fine with an 8 core CPU), you shouldn't have any issues with running out of memory with this small of a dataset. Running the Drosophila or Mouse Cortex dataset takes up considerably more RAM (my 64 GB machine chokes sometimes), but the Follicle example is much smaller. Perhaps try running the test script line by line and determine where the error is occurring?
