### ISSUE TITLE
AddNoise not found

### ISSUE THREAD

**Issue by NKalavros** [fmaseda/DEEPsc#2]
Hello,

Been trying to run DEEPsc and have been running into a problem with with ```MeasureMatchingRobustness```. The network trains just fine, but during the creation of the ```NoisyAtlas```, it complains that the ```AddNoise``` function was not found.

EDIT: Works if I exchange AddNoise to awgn

I'm using Matlab/2021a at the moment, but I've tried several other versions (2019b, 2020a, 2020b)

Thank you

**Comment by fmaseda** [comment]
Thanks for pointing this out. I've just pushed an update which added the AddNoise.m file you need.
